### ISSUE TITLE
Upload Wallpaper

### ISSUE THREAD

**Issue by oisonan1999** [AmrDeveloper/Askme#6]
When I upload wallpaper I always get this error :"Update Wallpaper Failure"
How can I fix this? Thank you so much

**Comment by AmrDeveloper** [comment]
Hello @oisonan1999,

I updated the build doc, 

in the server directory, you need to create storage/avatar and storage/wallpaper directories to save images,

the avatar works find with you because I pushed the avatar directory with the test image, 

so in the server directory, open your terminal and write

```
mkdir storage
cd storage
mkdir avatar
mkdir wallpaper
```

Note: don't write mkdir avatar if you have already one

Thanks
